import io
import re
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import cm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import HRFlowable, Paragraph, SimpleDocTemplate

from app.analysis.schemas import CorrectionPair


FONTS_DIR = Path(__file__).parent / "fonts"
FONT_REGULAR = FONTS_DIR / "Amiri-Regular.ttf"
FONT_BOLD = FONTS_DIR / "Amiri-Bold.ttf"

PRIMARY_COLOR = colors.Color(0.10, 0.20, 0.60)
WATERMARK_OPACITY = 0.12


def _register_fonts() -> tuple[str, str]:
    regular = "Helvetica"
    bold = "Helvetica-Bold"

    if FONT_REGULAR.exists():
        pdfmetrics.registerFont(TTFont("Amiri-Regular", str(FONT_REGULAR)))
        regular = "Amiri-Regular"
    if FONT_BOLD.exists():
        pdfmetrics.registerFont(TTFont("Amiri-Bold", str(FONT_BOLD)))
        bold = "Amiri-Bold"

    return regular, bold


def _prep_text(text: str) -> str:
    """
    Pre-process Arabic text for correct ReportLab rendering.
    Arabic needs reshaping (letter joining) and BiDi reordering (RTL→LTR buffer).
    Latin text passes through unchanged.
    """
    if not re.search(r"[\u0600-\u06FF]", text):
        return text
    try:
        import arabic_reshaper
        from bidi.algorithm import get_display
        return get_display(arabic_reshaper.reshape(text))
    except ImportError:
        return text


def _draw_watermark(canvas, doc):
    """Tile the SharafAI watermark diagonally across the page."""
    w, h = A4
    canvas.saveState()
    canvas.translate(w / 2, h / 2)
    canvas.rotate(45)
    canvas.setFont("Helvetica-Bold", 48)
    canvas.setFillColorRGB(0.55, 0.55, 0.55, alpha=WATERMARK_OPACITY)
    for dy in range(-3, 4):
        for dx in range(-2, 3):
            canvas.drawCentredString(dx * 200, dy * 100, "SharafAI")
    canvas.restoreState()


def generate_corrected_pdf(
    suggestions: list[CorrectionPair],
    candidate_name: str = "",
) -> bytes:
    """
    Build a corrected CV PDF containing all suggested text corrections,
    with the SharafAI watermark on every page.

    Returns raw PDF bytes ready to stream back to Flutter.
    """
    regular, bold = _register_fonts()

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        rightMargin=2 * cm,
        leftMargin=2 * cm,
        topMargin=2.5 * cm,
        bottomMargin=2 * cm,
    )

    title_style = ParagraphStyle(
        "Title", fontName=bold, fontSize=18,
        textColor=PRIMARY_COLOR, spaceAfter=6, alignment=TA_CENTER,
    )
    sub_style = ParagraphStyle(
        "Sub", fontName=regular, fontSize=9,
        textColor=colors.grey, spaceAfter=4, alignment=TA_CENTER,
    )
    section_style = ParagraphStyle(
        "Section", fontName=bold, fontSize=12,
        textColor=PRIMARY_COLOR, spaceBefore=12, spaceAfter=4,
    )
    label_style = ParagraphStyle(
        "Label", fontName=regular, fontSize=9,
        textColor=colors.grey, spaceAfter=2,
    )
    body_style = ParagraphStyle(
        "Body", fontName=regular, fontSize=10, leading=14, spaceAfter=6,
    )
    suggested_style = ParagraphStyle(
        "Suggested", fontName=regular, fontSize=10, leading=14, spaceAfter=10,
        textColor=colors.Color(0.0, 0.45, 0.2),
    )

    header = f"Corrected CV — {candidate_name}" if candidate_name else "Corrected CV"

    story = [
        Paragraph(_prep_text(header), title_style),
        Paragraph(_prep_text("Generated by SharafAI"), sub_style),
        HRFlowable(width="100%", thickness=1, color=PRIMARY_COLOR, spaceAfter=16),
    ]

    if not suggestions:
        story.append(
            Paragraph(_prep_text("No corrections needed — your CV looks great!"), body_style)
        )
    else:
        grouped: dict[str, list[CorrectionPair]] = {}
        for s in suggestions:
            grouped.setdefault(s.section, []).append(s)

        for section_name, pairs in grouped.items():
            story.append(Paragraph(_prep_text(section_name), section_style))
            for pair in pairs:
                story.append(Paragraph(_prep_text("Original:"), label_style))
                story.append(Paragraph(_prep_text(pair.original), body_style))
                story.append(Paragraph(_prep_text("✓ Suggested:"), label_style))
                story.append(Paragraph(_prep_text(pair.suggested), suggested_style))

    doc.build(story, onFirstPage=_draw_watermark, onLaterPages=_draw_watermark)
    return buf.getvalue()
